import Footer from "@/components/footer";
import HeaderWrapper from "@/components/wrapper/header-wrapper"; // ✅ חדש
import ThemeRegistry from "@/components/theme-registry/theme-registry";
import SessionProviderWrapper from "@/components/wrapper/session-provider-wrapper";
import { Box } from "@mui/material";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "My App",
  description: "Generated by Next.js",
  icons: { icon: "/InaAppLogo.png" },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ThemeRegistry>
      <html lang="he" dir="rtl">
        <body
          style={{
            display: "flex",
            flexDirection: "column",
            minHeight: "100vh",
            margin: 0,
          }}
        >
          <SessionProviderWrapper>
            <HeaderWrapper /> {/* ✅ עכשיו ה-header מתנהג לפי הדף */}
            <main style={{ flex: 1 }}>{children}</main>
            <Footer />
          </SessionProviderWrapper>
        </body>
      </html>
    </ThemeRegistry>
  );
}
