import Footer from "@/components/footer";
import Header from "@/components/header";
import ThemeRegistry from "@/components/theme-registry/theme-registry";
import SessionProviderWrapper from "@/components/wrapper/session-provider-wrapper";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "My App",
  description: "Generated by Next.js",
  icons: { icon: "/InaAppLogo.png" },
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <ThemeRegistry>
      <html lang="he" dir="rtl">
        <body style={{ display: "flex", flexDirection: "column", minHeight: "100vh", margin: 0 }}>
          <SessionProviderWrapper>
            <Header />
            <main style={{ flex: 1 }}>{children}</main>
            <Footer />
          </SessionProviderWrapper>
        </body>
      </html>
    </ThemeRegistry>
  );
}
